### PR TITLE
feat!: migrate autoware_msgs

### PR DESCRIPTION
**Pull request by mozhoku**
## Description
Updated message types in the project. 
Changes can be seen as a table [here.](https://docs.google.com/spreadsheets/d/1fiB7pYaDOWxb1L8SBA07QyV10KtVoaPFl9dfIxa3GpY/edit?usp=sharing) 

- Removed old "autoware_auto_xxx" messages.
- Added new "autoware_xxx" messages. [Link](https://github.com/autowarefoundation/autoware_msgs)
- Updated message types in the scripts.
- Updated docs.
- Refactored **"V2IRos2Publisher.cs"** to publish **"TrafficLightGroupArray"**. (**"TrafficSignalArray"** is planned for removal [here](https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_perception_msgs/CMakeLists.txt).)
- Cherry picked: https://github.com/tier4/AWSIM/commit/c5908a6ca74c403fc2f3404a1fe3665a453f8930 which adds new msgs for Windows.

### Related links

- https://github.com/autowarefoundation/AWSIM-Labs/issues/88

## Tests performed

Tested in Ubuntu with Autoware.

## Effects on system behavior

Added new message types for up to date Autoware.
Removed old `autoware_auto_xxx` messages.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by lchojnack** [comment]
@mozhoku 
- The AWSIM after migration is working with Autoware on Linux
  https://youtu.be/-aLUUpk5lK0

- I've also checked the V2I feature, and works as expected
  Screenshot_20240610_094711

---
What I would consider to change:
- there are still mentions of `autoware_auto_msgs` in docs 
   - docs/Components/ROS2/AddACustomROS2Message/index.md
   - docs/Components/ROS2/ROS2ForUnity/index.md
   - docs/Components/Sensors/VehicleStatusSensor/index.md
   - docs/Components/Vehicle/EgoVehicle/index.md
   - docs/GettingStarted/QuickStartDemo/index.md
- update `ScenarioSimulatorConnector` to support `autoware_msgs` 
  - that could be done in the next PR because `scenario_simulator_v2` uses `autoware_auto_msgs` on the main branch so far
  - Note: if you would like to update `ScnarioSimulatorConnector` you can cherry-pick this commit https://github.com/tier4/AWSIM/pull/313/commits/5f01307e08db55093a07efa68ba93b8ce51a71ed
- this PR doesn't update the `autoware_auto_msgs` for Windows
  -  Note: if you would like to add  `autoware_auto_msgs` for Windows you can cherry-pick this commit https://github.com/tier4/AWSIM/pull/313/commits/c5908a6ca74c403fc2f3404a1fe3665a453f8930

**Comment by mozhoku** [comment]
@lchojnack I've added the windows messages as you suggested and made the mentioned changes in the docs.

I've noticed there are old message types present in the Windows msgs. Should we keep the old ones @lchojnack @xmfcx, or would you like me to remove them?

**Comment by lchojnack** [comment]
@mozhoku I would prefer to remove the old autoware_auto_msgs

**Comment by mozhoku** [comment]
Removed old message types used by the Windows builds. I was not able to test it yet though.

**Comment by mozhoku** [comment]
@lchojnack @xmfcx ping.

**Comment by lchojnack** [comment]
@mozhoku I'm reviewing right now. Please give me some time.

**Comment by lchojnack** [comment]
@mozhoku 
- I've tested if AWSIM can be run on Windows, and it works as expected
  awsim_labs_autoware_msgs_windows
- I've tested if AWSIM can be run with Autoware on Linux, and it works as expected 


[awsim_labs_test.webm](https://github.com/autowarefoundation/AWSIM-Labs/assets/8416175/72950981-6c76-478d-b8fe-53cb32e3644b)


LGTM :+1:

**Review by lchojnack — APPROVED** [review]

**Pull request merged**
