### PR TITLE
feat: VPP CE Integration

### PR DESCRIPTION
**Pull request by mozhoku**
## Description

This PR replaces current vehicle dynamics with Vehicle Physics Pro. This will allow users to observe more realistic vehicle behaviors from the simulation.

You need to add the following scripts to an VPP configured vehicle to be able to drive it with Autoware:

- `AutowareVPPAdapter.cs`: Used for applying the control inputs to the vehicle.
- `Ros2ToVPPInput.cs`: Used for receiving the control inputs from the Autoware.
- `VPPVehicleSignalHandler.cs`: Used for handling the signals from the vehicle.
- `VPPToRos2Publisher.cs`: Used for publishing the vehicle state to the Autoware.

Other new stuff & changes:
- The vehicle in the launch command has changed. (Details in docs.)
- Calibrated new pedal maps for the default Lexus vehicle. Please put these files into the raw_vehicle_cmd node. Otherwise pedal percentages are insufficient for vehicle to accelerate properly. (Details in docs.)  

Detailed steps for the integration is explained in the docs.

[Updated Pedal Maps](https://drive.google.com/drive/folders/1S0fcNHzkiF3F03hWqonQW8SYKPb2zQo-?usp=sharing)

### Related links

**Main Issue**
- https://github.com/autowarefoundation/AWSIM-Labs/issues/108

**Related Issues/PRs**
- https://github.com/autowarefoundation/autoware/issues/5106
- https://github.com/autowarefoundation/awsim_labs_vehicle_launch/pull/1
- https://github.com/autowarefoundation/autoware/pull/5166
## Tests performed

Tested with Autoware in the editor and the binary build.
[Comparison with Main Branch](https://youtu.be/oTl1rWWoBQw)
[Test drive from Editor](https://www.youtube.com/watch?v=-oV3onP0FmI)
[Test drive from Binary](https://www.youtube.com/watch?v=IliN5FoFKkQ)

## Effects on system behavior

Low fps when running with Autoware from the editor.
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mozhoku** [comment]
Progress vid: https://youtu.be/ZrvKUv_EE1U

**Comment by mozhoku** [comment]
Running from editor causes low fps compared to binary build.

Driving videos with adjusted vehicle specs that I was able to find from the web. 

- Unfortunately I couldn't find any engine torque/power graphs for the `Lexus RX450h 2015` online so I tried to create a graph that satisfies available information. This car has electric motors working with the engine. simulation does not take these into consideration. I also did not take this into consideration when adjusting the engine torque/power graph.

- Only info I had about the combustion engine was `MaxPower@RPM` and `MaxTorque@RPM`. This is the graph that satisfies the info at hand, visualized in VPP:
image

- As for the gear ratios, the vehicle has [CVT](https://en.wikipedia.org/wiki/Continuously_variable_transmission). Afaik these don't have set gear ratios and I couldn't find any info regarding to the gear ratios. I left them as they are.

- I didn't touch the `differential` settings in the `vehicle driveline` neither.

I've calibrated the pedal maps for the updated vehicle with the [accel_brake_map_calibrator](https://autowarefoundation.github.io/autoware.universe/pr-2609/vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/)

Videos with Autoware actuation commands: 
[Test drive from Editor](https://www.youtube.com/watch?v=-oV3onP0FmI)
[Test drive from Binary](https://www.youtube.com/watch?v=IliN5FoFKkQ)

**Comment by Aysenayilmaz** [comment]
I didn’t encounter any issues when controlling the vehicle with the keyboard. Compared to the previous version, it offered a more realistic driving experience. Thank you for your work! 

When I tried driving with Autoware, I encountered a few issues:
  -  A command had to be added to drive the vehicle with Autoware. The part 'launch_vehicle_interface:=true' wasn't mentioned in the documentation.
   - Changes were needed in the brake_map.csv file values.
   - Before switching to autonomous driving, you need to enable and disable keyboard control.
   - The vehicle couldn’t turn properly in corners. (There was no issue with keyboard driving).

**Comment by mozhoku** [comment]
The issue about "vehicle turning corners" works properly in default `AutowareSimulation` scene. 
It fails to drive when launched from the `Loader` scene.
I'll look into it.

**Comment by mozhoku** [comment]
Here is the side by side comparison:

https://youtu.be/oTl1rWWoBQw

**Comment by Aysenayilmaz** [comment]
While driving the vehicle I can move the vehicle forward even though I haven't enabled keyboard control from the UI. But aside from that, everything else seems to be fixed. 

https://youtu.be/NFdxtvFaGvU

**Review by Aysenayilmaz — APPROVED** [review]

**Pull request merged**
