### PR TITLE
update: set framerate to 60

### PR DESCRIPTION
**Pull request by mozhoku**
## Description

Exposed target framerate to editor under the AutowareSimulation.cs and defaulted to 60. 

- If you enable Vsync from the Project Settings, Unity will ignore this value.

### Related links

- https://github.com/autowarefoundation/AWSIM/issues/40

## Tests performed

Tested in editor.

Not applicable.

## Effects on system behavior

Limits the framerate to 60.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
What happens if both vsync is on and a frame rate is set from the script?

**Comment by xmfcx** [comment]
Could you discard the scene file changes and reapply only this change?
Right now it has a large diff for some reason.

**Comment by mozhoku** [comment]
> What happens if both vsync is on and a frame rate is set from the script?

Unity ignores frame limit set by the user. Here is the Unity documentation related to this: https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html

**Comment by mozhoku** [comment]
> Could you discard the scene file changes and reapply only this change? Right now it has a large diff for some reason.



I've only exposed the targetframerate variable to editor via AutowareSimulation.cs and set it to 60. 

Okay I'll remove it.

**Comment by xmfcx** [comment]
Fix precommit pls

**Comment by xmfcx** [comment]
Rebase and add the scene changes, I didn't mean to remove them, just to reduce the diff size. But if the minimal changes still have huge scene diff, it's ok.

**Comment by mozhoku** [comment]
> Rebase and add the scene changes, I didn't mean to remove them, just to reduce the diff size. But if the minimal changes still have huge scene diff, it's ok.

Okay done.

**Review by xmfcx — APPROVED** [review]

**Pull request merged**
