### PR TITLE
feat: add traffic control ui

### PR DESCRIPTION
**Pull request by mozhoku**
Issue:
- https://github.com/autowarefoundation/AWSIM/issues/11

With this addition the traffic manager can be partially controlled from the Main Menu (esc). 
image

### CODE REVIEW

**Comment by mozhoku** [comment]
image

Camera output is overlapping the UI. Currently, this can be adjusted by scaling it or disabling it through the inspector. However, ideally, the camera output should be drawn behind the UI elements. To achieve this, I need to modify the rendering process to ensure the camera output is drawn in the correct order. Additionally, if there were multiple cameras, they could potentially obstruct the view on the screen. 

I'll create a separate issue for this later on.

**Comment by mozhoku** [comment]
This is how it looks at the moment:
https://youtu.be/P5qCVeOA-jI

**Comment by xmfcx** [comment]
Thanks for the updates, looks promising 🍀

Could you create an issue and a PR to put the Camera panels behind the Main Menu canvas?

**Comment by xmfcx** [comment]
Screenshot from 2024-03-28 13-49-56

Works well!

**Review by xmfcx — APPROVED** [review]

**Pull request merged**
