### PR TITLE
feat: update ui

### PR DESCRIPTION
**Pull request by mozhoku**
## Description

Improvements for the UI.
 
- Added new side bar on the left that will hold all the UI elements. Can be toggled from screen or `Esc`.
- Graphy is moved into the side bar. Can be toggled on/off with `F3`.
- Timescale slider moved into the side bar.
- New hotkey for toggling traffic visibility: `Ctrl+T`
- Added new icons and animations for the UI.

### Related links
Issue:
- https://github.com/autowarefoundation/AWSIM/issues/63

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mozhoku** [comment]
Progress:
image

**Comment by xmfcx** [comment]
please rebase to the latest main

**Comment by mozhoku** [comment]
Progress:
image

**Comment by mozhoku** [comment]
Added some animations.
Progress:

https://youtu.be/FzU7C2QrsNE

**Comment by mozhoku** [comment]
Current status:
https://youtu.be/jI3zJ7mlSpY

**Comment by Aysenayilmaz** [comment]
When Graphy assetini is not added, the text fonts are not showing up. But when it's added, there's no issue, and the hotkeys are working fine.   
Screenshot from 2024-05-02 18-03-53

Screenshot from 2024-05-02 18-07-45

**Comment by xmfcx** [comment]
Please fix the https://github.com/autowarefoundation/AWSIM/actions/runs/8924123708/job/24509806240?pr=57 errors

**Review by Aysenayilmaz — APPROVED** [review]

**Pull request merged**
