### PR TITLE
feat!: upgrade the unity to new LTS 2022.3.21f1

### PR DESCRIPTION
**Pull request by Aysenayilmaz**
## Description
I updated Awsim's Unity version to LTS 2022.3.21f1. I got errors in the console due to some library conflicts.I had 3 of them in different versions from some libraries. I deleted the others except the most updated ones because they caused an error. 

### Related links

Fixes : 

- https://github.com/autowarefoundation/AWSIM/issues/6

## Tests performed

- [ ] Open the AutowareSimulation.scene 
- [ ] Run the scene. 

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by xmfcx — CHANGES_REQUESTED** [review]
Could you disable the keyboard control script from the vehicle?

**Review by mozhoku — APPROVED** [review]
I think we can merge it. I've tested it in editor no issues. But in the build, there was some visual issues with the speedtree8 shaders. That can be adjusted later with a small update.

**Comment by xmfcx** [comment]
Screenshot from 2024-03-29 16-49-00

In the built version, the rendered in vehicle camera is broken, it leaves artifacts.

Did this also exist in the previous builds?

**Comment by mozhoku** [comment]
> Screenshot from 2024-03-29 16-49-00
> 
> In the built version, the rendered in vehicle camera is broken, it leaves artifacts.
> 
> Did this also exist in the previous builds?

I didn't notice this issue in previous builds. It's caused by setting the sensor camera's background type to **Skybox**. After changing it to **Solid Color** ghosting is gone.

Update 01: After baking the light to the scene and changing camera background type to Skybox it worked fine.

Update 02: Tested same settings in another ubuntu pc. Ghosting issue still persists.

Update 03: Enabling "Post Process" for the camera solved the issue. For some reason it is not clearing older frames otherwise.

**Left Output: PP Enabled || Right Output: PP Disabled**

image

**Review by mozhoku — CHANGES_REQUESTED** [review]
@Aysenayilmaz Please enable the Post Processing for the Camera's in the scene. It can be found under any Camera component > Rendering:

image

**Review by mozhoku — APPROVED** [review]

**Review by xmfcx — APPROVED** [review]

**Pull request merged**
