### PR TITLE
feat: enable multi scene setup

### PR DESCRIPTION
**Pull request by lchojnack**
### Related links

Related to:
- https://github.com/autowarefoundation/AWSIM-Labs/issues/34

## Tests performed

- AWSIM with Autoware
  https://youtu.be/PhMqlUjqPBY
  

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by lchojnack** [comment]
@xmfcx 
Here is the autoware exact of my setup [autoware_exact.repos.txt](https://github.com/user-attachments/files/16064679/autoware_exact.repos.txt)

**Comment by lchojnack** [comment]
I've enabled:
- Resetting EGO position
- Traffic Control settings
- Bird-eye view

What is still missing:
- Toggle EGO sensor topics
- Graphics settings
- Camera image view

The test of reset EGO position, traffic control settings, bird-eye view in the video below
https://youtu.be/BDl49MYPYlw

**Comment by lchojnack** [comment]
From the last update I've enabled and tested (https://youtu.be/5lW5NF8SanM):
- toggle sensors
- graphics settings
- time scale test
- camera test


What is still not working as expected:
- warnings `The referenced script (Unknown) on this Behaviour is missing!` in the Editor console 
- white rectangular in the bottom left corner
- different color scheme 
   | LoaderScene | AutowareSimulator | 
   | ---- | ----| 
   | image | image |

**Comment by lchojnack** [comment]
@xmfcx @mozhoku @Aysenayilmaz 
The feature (https://github.com/autowarefoundation/AWSIM-Labs/pull/22) is enabled by default
The PR is ready for review. Please let me know your feedback.

**Comment by Aysenayilmaz** [comment]
I tried adding a new scene and didn't encounter any issues, except for the lack of an FPS limit. And maybe shortcut key or a button could be added to return to the load screen. 
Thanks for your work!

**Review by mozhoku — CHANGES_REQUESTED** [review]
@lchojnack  
Toggling the `main camera render` from the UI doesn't disable main camera in the loaded scenes.
image
 
Other than that LGTM. 
Thanks for the PR :pray:

**Comment by lchojnack** [comment]
@Aysenayilmaz @mozhoku 
Thank you for review
I've fixed:
- FPS limit 
- Toggling `main camera render`

Below is the video showing that the PR works with the latest main Autoware (13.08.2024) 
https://youtu.be/VkXowiZ9WP8

**Review by mozhoku — APPROVED** [review]

**Pull request merged**
