### PR TITLE
feat: dynamic sensor placement

### PR DESCRIPTION
**Pull request by SujayAmberkar**
## Description

- Read transforms from URDF file and place sensors dynamically.
- Place the URDF file in the Externals folder and provide the path in the "Dynamic Sensor Placement" Editor tool.
- Path will be ./Assets/AWSIM/Externals/your_urdf_file.urdf

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by SujayAmberkar** [comment]
[DynamicSensorPlacement.webm](https://github.com/autowarefoundation/AWSIM/assets/38327075/48ef49e7-21b1-44bd-9222-33933c7bbb2f)

- In the video, initially, I moved all the sensors to a random position. At about 0:18 in the video, I opened the Dynamic Sensor Placement Tool with a path to the URDF file and clicked the "Place Sensors" button that placed all the sensors according to the URDF file.

- Now a few things to notice here,
  - Following are the sensors that will be automatically assigned the transforms, so the direct child of these game objects must have position and rotation = [0,0,0]. I've not made this change in this PR but we need this for the tool to work properyly.
  - Screenshot from 2024-05-15 19-26-40
  - Finally, we should have the "velodyne_top_base_link" game object with VelodyneVLP16 as its child for the top lidar otherwise the top lidar won't be placed automatically. You can see the last highlighted game object in the screenshot. I only created the "velodyne_top_base_link" game object temporarily and did not change the prefab in my PR as I don't know what might break.
  
  Here's a urdf file to test
[awsim_vehicle.zip](https://github.com/autowarefoundation/AWSIM/files/15323236/awsim_vehicle.zip)

**Comment by mozhoku** [comment]
@SujayAmberkar 

I've tested the PR and it's working with the instructions provided.

I just want to say that:
_by default the parent "link" objects are holding the position of the sensor:_
image

_and the sensor objects are holding the rotations:_
image

_I don't like this approach personally. There is no need to have different objects to define the rotation and position seperately._

- Could you create a documentation in docs about how to use this tool. And please add the changes needed to make it work on the default sensors.

- Please fix the pre-commit errors.

_It would be nice if it could instantiate the sensors but that's a PR for another day._ :+1:

**Comment by SujayAmberkar** [comment]
@mozhoku I've made the required changes to the prefab, fixed the pre-commit errors, and updated the docs. Do I need to worry about the other 2 tasks(line checker and build-test)?

**Comment by mozhoku** [comment]
> @mozhoku I've made the required changes to the prefab, fixed the pre-commit errors, and updated the docs. Do I need to worry about the other 2 tasks(line checker and build-test)?

@SujayAmberkar No need to worry about those two.

If you can fix the DCO we can merge it to main. Also pre-commit again. 😓 
https://github.com/apps/dco

**Comment by mozhoku** [comment]
I can set DCO to pass since you have signed last commits.

**Comment by SujayAmberkar** [comment]
@mozhoku apologies, I was trying to fix the pre-commits and some indentation in docs since it wasn't appearing like it is on my machine. But now it's fixed

**Review by mozhoku — APPROVED** [review]

**Pull request merged**
